app = "uninotes"
primary_region = "sin"

[build]

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "database"
  CACHE_STORE = "database"
  QUEUE_CONNECTION = "database"
  FILESYSTEM_DISK = "public"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "uninotes_data"
  destination = "/var/www/html/storage/app/public"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
